### ISSUE TITLE
Horizontal slider

### ISSUE THREAD

**Issue by TrixieL** [erichbehrens/react-animated-slider#26]
Hi! 

Thanks for this component! However, I am having trouble as the <Horizontal> animates as vertical. Like in here: https://codesandbox.io/s/p582xl40j

Both components have same effects.

**Comment by luangjokaj** [comment]
Hey @TrixieL sorry for the late reply, it was a busy holiday season, happy new year 😄 

I suggest to import only one css file horizontal.css or vertical.css. Please check the updated code sandbox: https://codesandbox.io/s/p582xl40j

**Comment by TrixieL** [comment]
Thanks a lot! Happy new year too :)
