### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by ShelbyMedd06** [erichbehrens/react-animated-slider#35]
When you set a manual duration using the duration property it breaks the sliding transition animation. The transition animation is set in the CSS at 2s hardcoded, so when you set your duration to anything less than that (ex. duration={1000}), it animates half way and then jumps the rest of the way.

**Comment by erichbehrens** [comment]
Hi Shelby, animations are controlled from the css and the duration prop is used to tell the component how long the css animations are, so it can switch from the "animating" state to the "static" state only after all animations have completed. If you want to change the duration of the animations you have to override the css and pass the new value to the duration prop.
