### ISSUE TITLE
Werid Error during multiple usage of Slider 

### ISSUE THREAD

**Issue by Asher978** [erichbehrens/react-animated-slider#52]
I am using the slider component in various parts of my site, in some cases multiple times on one page and keep getting this error that i cant's seem to figure out. 

Definitely want to avoid this for production. This error occurs after i've changed the route and navigated to a different page.

`Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

**Comment by erichbehrens** [comment]
Hi @Asher978 , I was able to reproduce the error by unmounting the component while an animation is playing. Fixed it in #55 and released to `v1.1.3`. Does it solve your issue?

**Comment by Asher978** [comment]
It absolutely does. Thanks for your help.
