### ISSUE TITLE
Need more event listeners.

### ISSUE THREAD

**Issue by ZeroCho** [erichbehrens/react-animated-slider#66]
First, thank you for great slider!

I think it would be better if there are more event listeners such as onClickPrevBtn, onClickNextBtn, or
onBeforeSlideChange.

Currently, there's only one event listener `onSlideChange` which called after slide has changed. I need something called before change.

**Comment by erichbehrens** [comment]
Hi @ZeroCho , can you give me more information about your use case? Do you only want to listen to the event or do you also want to cancel it and prevent the navigation?
