### ISSUE TITLE
Duration change is not reflected in animation.

### ISSUE THREAD

**Issue by ZeroCho** [erichbehrens/react-animated-slider#67]
As far as I know, default duration is 2000.
When I change duration to 1000, animation speed still acts like duration is 2000 so that it prevents smooth animation.

**Comment by luangjokaj** [comment]
@ZeroCho in your CSS, you have to change also:
```
&.animateIn,
&.animateOut {
	transition: all 2s ease;
}
```
From 2s to 1s.
