### ISSUE TITLE
There's no possible to custom the arrows

### ISSUE THREAD

**Issue by francisrod01** [erichbehrens/react-animated-slider#69]
Hi there! I need to custom the arrows to use in my template.
I'd like to replace the jQuery slideshow effect to this animated slider.

In my template the `arrows` are out of the slider div. This gives me customization in the layout.
More information about the slideshow in my template:
http://prototype-learn.webflow.io/

**Comment by erichbehrens** [comment]
Hi @francisrod01 , here you can find an example implementation for your use case: https://codesandbox.io/s/62p606xymw

 There's also an option to provide `previousButton` and `nextButton` components to the slider, but this would give you less customization freedom in respect to the dom.

**Comment by francisrod01** [comment]
@erichbehrens I'll see it tonight. Thanks! :)
