### ISSUE TITLE
Infinite slide does not work if there only 2 items

### ISSUE THREAD

**Issue by bicomo** [erichbehrens/react-animated-slider#80]
This can be reproduced on the demo Codesandbox Playground as well, if the items are reduced to 2, the slide does not go back to the first item once all are rotated.

**Comment by Shreerang** [comment]
This is correct. If there are only 2 slides then `infinite={true}` does not work.

**Comment by Shreerang** [comment]
Also "`autoplay={2000}`" does not work with 2 slides!
