### ISSUE TITLE
change slide? (or controlled behaviour)?

### ISSUE THREAD

**Issue by rodobodolfo** [erichbehrens/react-animated-slider#85]
Hi! is it possible to make the slider chnage to next item via a controlled behaviour?
I mapped slideIndex to the state but it wont work... Basically I want to add a nextSlide feature to the button...

Thanks!

**Comment by erichbehrens** [comment]
Hi, please see this example provided in #69 for controlling the slider with external buttons: https://codesandbox.io/s/62p606xymw . The relevant part is using `sliderRef`.
