### ISSUE TITLE
An image slide in slider 

### ISSUE THREAD

**Issue by Brahmrshi1** [erichbehrens/react-animated-slider#89]
Hello 

I am Trying your package for creating a slider for a website but that time I am facing an issue like this:
In slider when I am passing background image that time on run time only the first content image is displayed for all slides. The other is not changed, only contents are changed. 
So pls tell me what to do .....
Looking forward to a response

**Comment by erichbehrens** [comment]
Hi,

How are you setting the background? It should be set to each slide with inline style or by using element id or specific class names for each slide. Here you can find a basic example with inline style: https://codesandbox.io/s/62p606xymw

Can you reproduce the issue on https://codesandbox.io ?

**Comment by Brahmrshi1** [comment]
Sorry For Late Comment I definitely Try it and give you the response as soon possible. For Codesndbox code I try my best to create and share that with you with the same code that I try first.
