### ISSUE TITLE
How to change next and prev button 

### ISSUE THREAD

**Issue by itsgratien** [erichbehrens/react-animated-slider#90]
hey, how to change color next button and prev button or remove and add an svg image without using default SVG.

thanks.

**Comment by alexedtionweb** [comment]
all on css.
.previousButton,
.nextButton {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  z-index: 10;
  background: url('/PATH_TO/images/previousButton.svg') no-repeat center center / 16px;
  width: 32px;
  height: 32px;
  text-indent: -9999px;
  cursor: pointer;
}

.previousButton:hover,
.nextButton:hover {
  background: url('PATH_TO/images/previousButton.svg') no-repeat center center / 16px;
}

.previousButton {
  left: 0;
  -webkit-transform: rotate(180deg) translateY(calc(50% + 0px));
  transform: rotate(180deg) translateY(calc(50% + 0px));
}

**Comment by itsgratien** [comment]
Thank you @alexedtionweb
